version: '3.8'

networks:
  irish-nfts:
    driver: bridge

services:

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: irish_nfts_sqlserver
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "!rishNFTs2023"
      ACCEPT_EULA: "Y"
    networks:
      - irish-nfts

  irishnfts:
    build: ./Front-End/IrishNFTs.MVC
    image: irishnfts:mvc
    container_name: irishnfts_mvc
    ports:
      - "5000:5000"
    depends_on:
      - productsapi
      - ordersapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - irish-nfts

  productsapi:
    build: ./Back-end/ProductsAPI
    image: irishnfts:productsapi
    container_name: irishnfts_productsapi
    ports:
      - "5001:5001"
    depends_on:
      - sqlserver
    networks:
      - irish-nfts

  ordersapi:
    build: ./Back-end/OrdersAPI
    image: irishnfts:ordersapi
    container_name: irishnfts_ordersapi
    ports:
      - "5002:5002"
    depends_on:
      - sqlserver
    networks:
      - irish-nfts
